/**
 * ISTQB® Certified Tester Foundation Level (CTFL) v4.0.1
 * Practice Exam Questions - Sample Exam Set D
 *
 * Source: ISTQB_CTFL_v4.0_Sample-Exam-D v1.5
 * Copyright © International Software Testing Qualifications Board
 * Used with attribution under the ISTQB® copyright notice for non-commercial use.
 */

import type { ExamQuestion } from '@/types';

export const questions: ExamQuestion[] = [
  {
    id: 1,
    domain: 'Chapter 1: Fundamentals of Testing',
    question: 'Which of the following is a typical test objective?',
    options: [
      'Finding and fixing defects in the test object',
      'Maintaining effective communications with developers',
      'Validating that legal requirements have been met',
      'Building confidence in the quality of the test object',
    ],
    correctAnswer: 3,
    explanation: 'Building confidence in the quality of the test object is a typical test objective, achieved by executing tests that pass. Fixing defects is not a test activity, and checking legal requirements is verification, not a typical test objective.',
  },
  {
    id: 2,
    domain: 'Chapter 1: Fundamentals of Testing',
    question: 'A designer documents a design for a user interface that does not suitably address disabled users because the designer is tired. The programmer implements the user interface in line with the design but as they are working under severe time pressure, they do not include suitable exception handling in their program code for bonus calculations. When the operational system is used, complaints are made by some disabled users about the interface and the company is subsequently fined by the relevant regulatory authority. No one notices that bonus calculations are sometimes incorrect. Which of the following statements is CORRECT?',
    options: [
      'The miscalculation of bonuses is a defect that occasionally occurs',
      'The fine received for failing to address some disabled users is a failure',
      'The programmer working under severe time pressure is a root cause',
      'The design of the user interface includes a designer error',
    ],
    correctAnswer: 2,
    explanation: 'The programmer made an error (omitting exception handling) caused by severe time pressure, which is the root cause of the subsequent defect. The miscalculation is a failure (not a defect), and the fine itself is not a failure of the system under test.',
  },
  {
    id: 3,
    domain: 'Chapter 1: Fundamentals of Testing',
    question: 'Test conditions are being used by testers to generate test cases and execute tests. Even though the test conditions remain the same, the test cases are varied each time. Which of the following principles of testing is being addressed through the variation of test cases?',
    options: [
      'Tests wear out',
      'Absence-of-defects fallacy',
      'Early testing saves time and money',
      'Defects cluster together',
    ],
    correctAnswer: 0,
    explanation: 'The tests wear out principle states that repeating identical tests on unchanged code is unlikely to find new defects. By varying test cases from the same test conditions, the risk of tests wearing out is reduced.',
  },
  {
    id: 4,
    domain: 'Chapter 1: Fundamentals of Testing',
    question: 'Given the following test tasks: (1) Derive test cases from test conditions, (2) Identify reusable testware, (3) Organize test cases into test procedures, (4) Evaluate the test basis and the test object. And the following test activities: A. Test analysis, B. Test design, C. Test implementation, D. Test completion. Which of the following BEST matches the tasks with the activities?',
    options: [
      '1B, 2A, 3D, 4C',
      '1B, 2D, 3C, 4A',
      '1C, 2A, 3B, 4D',
      '1C, 2D, 3A, 4B',
    ],
    correctAnswer: 1,
    explanation: 'The correct mapping is: Test design derives test cases from conditions (1B), test completion identifies reusable testware (2D), test implementation organizes cases into procedures (3C), and test analysis evaluates the test basis (4A).',
  },
  {
    id: 5,
    domain: 'Chapter 1: Fundamentals of Testing',
    question: 'Given the following testware: (i) Test completion report, (ii) Data held in a database used for test inputs and expected results, (iii) The list of elements needed to build the test environment, (iv) Documented sequences of test cases in execution order, (v) Test cases. Which of the following BEST shows the testware produced as a result of performing test implementation?',
    options: [
      'ii, iv',
      'iii, v',
      'i, ii, v',
      'i, iii, iv',
    ],
    correctAnswer: 0,
    explanation: 'Test implementation produces test procedures (documented sequences of test cases) and test data (database inputs and expected results). The test completion report is from test completion, environment requirements are from test design, and test cases are from test design.',
  },
  {
    id: 6,
    domain: 'Chapter 1: Fundamentals of Testing',
    question: 'Which of the following is MOST likely to describe a task performed by someone in a test management role?',
    options: [
      'Evaluate the test basis and the test object',
      'Define test environment requirements',
      'Assess testability of the test object',
      'Create the test completion report',
    ],
    correctAnswer: 3,
    explanation: 'The test management role primarily handles test planning, monitoring, control, and completion activities. Creating the test completion report is a key test management task, while the other options are test analysis and design tasks performed by the testing role.',
  },
  {
    id: 7,
    domain: 'Chapter 1: Fundamentals of Testing',
    question: 'Which of the following is an advantage of the whole team approach?',
    options: [
      'Improved communication between team members',
      'Decreased individual accountability for quality',
      'Faster deployment of deliverables to the end users',
      'Reduced collaboration with external business users',
    ],
    correctAnswer: 0,
    explanation: 'The whole team approach promotes robust communication and collaboration between team members. Each member remains equally accountable for quality, and the approach does not inherently reduce collaboration with external business users.',
  },
  {
    id: 8,
    domain: 'Chapter 1: Fundamentals of Testing',
    question: 'Given the following benefits and drawbacks of the independence of testing: (i) The testers work in a different location from the developers, (ii) Testers question the assumptions programmers make while writing code, (iii) A confrontational dynamic has been established between testers and developers, (iv) Developers have convinced themselves that testers are mostly accountable for quality, (v) Testers have different biases than those held by the developers. Which are MOST likely to be considered benefits?',
    options: [
      'i, iv',
      'ii, v',
      'i, iii, iv',
      'ii, iii, v',
    ],
    correctAnswer: 1,
    explanation: 'Benefits of test independence include testers questioning developer assumptions and bringing different biases/backgrounds. Working in different locations, confrontation, and reduced accountability for quality are all disadvantages.',
  },
  {
    id: 9,
    domain: 'Chapter 2: Testing Throughout the SDLC',
    question: 'Which of the following is a good testing practice that applies to all software development lifecycles?',
    options: [
      'Each test level has specific and distinct test objectives',
      'Test implementation and execution for a given test level should start during the corresponding development phase',
      'Testers should start test design as soon as drafts of the relevant work products become available',
      'Every dynamic testing activity has a corresponding static testing activity',
    ],
    correctAnswer: 0,
    explanation: 'Each test level has specific and distinct objectives because different forms of the test object (component vs. system) are tested at each level. Overlapping objectives would cause unnecessary duplication.',
  },
  {
    id: 10,
    domain: 'Chapter 2: Testing Throughout the SDLC',
    question: 'Which of the following is an example of a test-first approach to development?',
    options: [
      'Behavior-Driven Development',
      'Test Level Driven Development',
      'Function-Driven Development',
      'Performance-Driven Development',
    ],
    correctAnswer: 0,
    explanation: 'Behavior-Driven Development (BDD) is a well-known test-first approach. The other options are not recognized test-first development approaches in the ISTQB syllabus.',
  },
  {
    id: 11,
    domain: 'Chapter 2: Testing Throughout the SDLC',
    question: 'Which of the following is MOST likely to be a challenge encountered when implementing DevOps?',
    options: [
      'Making sure that non-functional quality characteristics are not overlooked',
      'Managing continuously changing test environments',
      'The need for more manual testers with suitable experience',
      'Setting up the test automation as part of the delivery pipeline',
    ],
    correctAnswer: 3,
    explanation: 'DevOps implementation requires setting up the delivery pipeline, introducing CI/CD tools, and establishing test automation as part of that pipeline. DevOps typically increases visibility of non-functional characteristics and reduces manual testing needs.',
  },
  {
    id: 12,
    domain: 'Chapter 2: Testing Throughout the SDLC',
    question: 'Which of the following BEST describes retrospectives?',
    options: [
      'Retrospectives allow team members to identify other team members who did not fully contribute to achieving quality as required by the whole team approach',
      'Retrospectives give testers an opportunity to identify activities that were successful so that these are retained when potential improvements are made in the future',
      'Retrospectives are where agile team members are allowed to voice their concerns about management and customers in a blameless environment',
      'Retrospectives give agile team members a forum where they focus on discussing the plan and technical decisions for the next iteration',
    ],
    correctAnswer: 1,
    explanation: 'Retrospectives discuss what worked well and should be retained, plus areas to improve. They are not for blaming individuals, criticizing stakeholders, or planning the next iteration.',
  },
  {
    id: 13,
    domain: 'Chapter 2: Testing Throughout the SDLC',
    question: 'Which of the following tests is MOST likely to be performed as part of functional testing?',
    options: [
      'The test checks that the sort function puts the elements of the list or array in ascending order',
      'The test checks whether the sort function completes sorting within one second of starting',
      'The test checks how easily the sort function can be changed from sorting ascending to sorting descending',
      'The test checks that the sort function still functions correctly when moved from a 32-bit to a 64-bit architecture',
    ],
    correctAnswer: 0,
    explanation: 'Checking that the sort function orders elements correctly is functional testing. The other options are non-functional: performance (time), maintainability (modifiability), and portability (32 vs 64-bit).',
  },
  {
    id: 14,
    domain: 'Chapter 2: Testing Throughout the SDLC',
    question: 'Which of the following is MOST likely to be a trigger that leads to maintenance testing of a currency exchange system?',
    options: [
      'The developers reported that changing the currency exchange system was difficult and the testers decided to check if this was true',
      'The refund option of the currency exchange system was removed as it did not always repay the correct amount to customers',
      'The agile team has started developing a user story that adds a new customer loyalty feature to the currency exchange system',
      'The language support option of the currency exchange system was used to enable both English and local language currency transactions',
    ],
    correctAnswer: 1,
    explanation: 'A system modification (such as removing the refund option as a fix) is a maintenance testing trigger. Adding a new feature involves testing the new feature plus regression, not maintenance testing per se.',
  },
  {
    id: 15,
    domain: 'Chapter 3: Static Testing',
    question: 'Which of the following CANNOT be examined by static testing?',
    options: [
      'Contract',
      'Test plan',
      'Encrypted code',
      'Test charter',
    ],
    correctAnswer: 2,
    explanation: 'Encrypted code is too complex for humans to interpret and not analyzable by most tools, so it cannot be examined by static testing. Contracts, test plans, and test charters are all human-readable and can be reviewed.',
  },
  {
    id: 16,
    domain: 'Chapter 3: Static Testing',
    question: 'Which of the following statements about the value of static testing is CORRECT?',
    options: [
      'The defect types found by static testing are different from the defect types that can be found by dynamic testing',
      'Dynamic testing can detect the defect types that can be found by static testing plus some additional defect types',
      'Dynamic testing can identify some of the defects that can be found by static testing but not all of them',
      'Static testing can identify the defect types that can be found by dynamic testing as well as some extra defect types',
    ],
    correctAnswer: 2,
    explanation: 'Some defects (e.g., unreachable code, non-executable work products) can only be found by static testing, while others (e.g., performance issues) only by dynamic testing. Dynamic testing finds only a subset of what static testing can find.',
  },
  {
    id: 17,
    domain: 'Chapter 3: Static Testing',
    question: 'Given the following descriptions of review activities: (1) Detected anomalies are deliberated upon, and determinations are reached regarding their status, ownership, and any further steps needed, (2) Defects are recorded, and any needed updates are addressed prior to the acceptance of the work product, (3) Reviewers employ techniques to come up with suggestions and questions about the work product and to spot anomalies, (4) The objective of the review and its schedule are established to ensure a focused and efficient review, (5) Participants are provided with access to the item being reviewed. Which of the following is the CORRECT sequence in the review process of the activities that correspond to the descriptions?',
    options: [
      '4 - 3 - 5 - 2 - 1',
      '4 - 5 - 3 - 1 - 2',
      '5 - 4 - 1 - 3 - 2',
      '5 - 4 - 3 - 2 - 1',
    ],
    correctAnswer: 1,
    explanation: 'The generic review process from ISO/IEC 20246 follows: Planning (4), Review initiation (5), Individual review (3), Communication and analysis (1), Fixing and reporting (2).',
  },
  {
    id: 18,
    domain: 'Chapter 3: Static Testing',
    question: 'Which participant in the review process is responsible for ensuring that the review meetings run effectively and that everyone at the meetings can voice their opinions freely?',
    options: [
      'Manager',
      'Moderator',
      'Chairperson',
      'Review Leader',
    ],
    correctAnswer: 1,
    explanation: 'The moderator (or facilitator) ensures review meetings run effectively, manages time, mediates discussions, and creates a safe environment. The review leader oversees the process, and the manager decides what to review and allocates resources.',
  },
  {
    id: 19,
    domain: 'Chapter 4: Test Techniques',
    question: 'You perform system testing of an e-commerce web application and are provided with the following requirement: REQ 05-017. If the total cost of purchases exceeds $100, the customer gets a 5% discount on subsequent purchases. Otherwise, the customer does not receive a discount. Which test techniques will be MOST helpful in designing test cases based on this requirement?',
    options: [
      'White-box test techniques',
      'Black-box test techniques',
      'Experience-based test techniques',
      'Risk-based test techniques',
    ],
    correctAnswer: 1,
    explanation: 'The requirement specifies the desired behavior of the test object without referring to its internal structure, so black-box techniques (like Boundary Value Analysis or Decision Table Testing) are most suitable. The threshold of $100 suggests important equivalence partition boundaries.',
  },
  {
    id: 20,
    domain: 'Chapter 4: Test Techniques',
    question: 'The system for selling cinema tickets calculates the discount type based on the client birth year (BY) and on the current year (CY) as follows: Let D be the difference between CY and BY, that is, D = CY - BY. If D < 0 then print the error message "birth year cannot be greater than current year". If 0 <= D < 18 then apply the student discount. If 18 <= D < 65 then apply no discount. If D >= 65 then apply the pensioner discount. Your test suite already contains two test cases: BY = 1990, CY = 2020, expected result: no discount; BY = 2030, CY = 2029, expected result: print the error message. Which of the following test data sets should be added to achieve full valid equivalence partitioning coverage for the discount type?',
    options: [
      'BY = 2001, CY = 2065',
      'BY = 1900, CY = 1965',
      'BY = 1965, CY = 1900',
      'BY = 2011, CY = 2029',
      'BY = 2000, CY = 2000',
    ],
    correctAnswer: [1, 4],
    correctAnswers: [1, 4],
    explanation: 'The existing test cases cover "no discount" (D=30) and "error" (D=-1). To complete valid equivalence partition coverage, the missing partitions "student discount" (0 <= D < 18) and "pensioner discount" (D >= 65) must be covered. Option b (D=65) covers pensioner, option e (D=0) covers student.',
  },
  {
    id: 21,
    domain: 'Chapter 4: Test Techniques',
    question: 'You are testing a temperature control system for a horticultural cold storage facility. The system receives the temperature (in full degrees Celsius) as the input. If the temperature is between 0 and 2 degrees inclusive, the system displays the message "temperature OK". For lower temperatures, the system displays the message "temperature too low" and for higher temperatures it displays the message "temperature too high". Using two-value boundary value analysis, which of the following sets of test inputs provides the highest level of boundary value coverage?',
    options: [
      '-1, 3',
      '0, 2',
      '-1, 0, 2, 3',
      '-2, 0, 2, 4',
    ],
    correctAnswer: 2,
    explanation: 'For two-value BVA, the boundary values are -1 (too low), 0, 2 (OK), and 3 (too high). Option c covers all four boundary values across the three equivalence partitions.',
  },
  {
    id: 22,
    domain: 'Chapter 4: Test Techniques',
    question: 'You are designing test cases based on the following decision table. R1 R2 R3 R4 R5 R6 R7. C1: Age 0-18 19-65 19-65 >65 0-18 19-65 >65. C2: Experience - 0-4 >4 - - - -. C3: Registered? NO NO NO NO YES YES YES. Category A A B B B D C. So far you have designed the following test cases: TC1: 19-year-old, unregistered man with no experience; expected result: category A. TC2: 65-year-old, unregistered woman with 5 years of experience; expected result: category B. TC3: 66-year-old, registered man with no experience; expected result: category C. TC4: 65-year-old, registered woman with 4 years of experience; expected result: category D. Which of the following test cases, when added to the existing set of test cases, will increase the decision table coverage?',
    options: [
      '66-year-old, unregistered man with no experience; expected result: category B',
      '55-year-old, unregistered woman with 2 years of experience; expected result: category A',
      '19-year-old, registered woman with 5 years of experience; expected result: category D',
      'No additional test case can increase the already achieved decision table coverage',
    ],
    correctAnswer: 0,
    explanation: 'Existing TCs cover rules R2, R3, R7, R6. Option a (66-year-old, unregistered, no experience) matches R4, which is uncovered. Options b and c duplicate R2 and R6 respectively, so they do not increase coverage.',
  },
  {
    id: 23,
    domain: 'Chapter 4: Test Techniques',
    question: 'You are applying state transition testing to the hotel room reservation system modeled by the following state transition table, with 4 states and 5 different events: Events. State Available NotAvailable ChangeRoom Cancel Pay. S1: Requesting S2 S3. S2: Confirmed S1 S4 S4. S3: Waiting list S2 S4. S4: End. Assuming all test cases start in the Requesting state, which of the following test cases, represented as sequences of events, achieves the highest valid transitions coverage?',
    options: [
      'NotAvailable, Available, ChangeRoom, NotAvailable, Cancel',
      'Available, ChangeRoom, NotAvailable, Available, Pay',
      'Available, ChangeRoom, Available, ChangeRoom, NotAvailable',
      'NotAvailable, Cancel, ChangeRoom, Available, Pay',
    ],
    correctAnswer: 1,
    explanation: 'The Available, ChangeRoom, NotAvailable, Available, Pay sequence covers 5 of 7 valid transitions. The two "Available" events trigger different transitions (S1->S2 and S3->S2), maximizing unique coverage.',
  },
  {
    id: 24,
    domain: 'Chapter 4: Test Techniques',
    question: 'Your test suite S for a program P achieves 100% statement coverage. It consists of three test cases, each of which achieves 50% statement coverage. Which of the following statements is CORRECT?',
    options: [
      'Executing S will cause all possible failures in P',
      'S achieves 100% branch coverage for P',
      'Every executable statement in P containing a defect has been run at least once during the execution of S',
      'After removing one test case from S, the remaining two test cases will still achieve 100% statement coverage',
    ],
    correctAnswer: 2,
    explanation: '100% statement coverage means each executable statement ran at least once, so any defect in those statements had the opportunity to be exercised. This does not guarantee failures will occur, branch coverage, or that one test case can be removed.',
  },
  {
    id: 25,
    domain: 'Chapter 4: Test Techniques',
    question: 'Why does white-box testing facilitate defect detection even when the software specification is vague, outdated or incomplete?',
    options: [
      'Test cases are designed based on the structure of the test object rather than the specification',
      'For each white-box test technique the coverage can be well-defined and easily measured',
      'White-box test techniques are very well designed to detect omissions in the requirements',
      'White-box test techniques can be used in both static testing and dynamic testing',
    ],
    correctAnswer: 0,
    explanation: 'White-box testing examines the actual implementation structure, so it can find defects like extra features in the code (accidental or deliberate) that are not in the spec. This independence from the specification is its key strength when specs are poor.',
  },
  {
    id: 26,
    domain: 'Chapter 4: Test Techniques',
    question: 'Which of the following is NOT anticipated by the tester while applying error guessing?',
    options: [
      'The developer misunderstood the formula in the user story for calculating the interest',
      'The developer wrote "FA = A*(1+IR^N)" instead of "FA = A*(1+IR)^N" in the source code',
      'The developer missed the seminar on new compound interest rate legislation',
      'The accuracy of the interest calculated by the system is not precise enough',
    ],
    correctAnswer: 2,
    explanation: 'Missing a seminar on legislation is a potential root cause of a defect, not an error, defect, or failure. Error guessing anticipates errors, defects, and failures based on tester knowledge, but is difficult for root causes unrelated to the test object itself.',
  },
  {
    id: 27,
    domain: 'Chapter 4: Test Techniques',
    question: 'Which of the following is true about exploratory testing?',
    options: [
      'Test cases are designed before the exploratory testing session starts',
      'The tester can perform test execution, but cannot perform test design',
      'Exploratory testing results are good predictors of the number of remaining defects',
      'During exploratory testing the tester may use black-box test techniques',
    ],
    correctAnswer: 3,
    explanation: 'During exploratory testing, testers can use any test techniques they find useful, including black-box techniques. Test design and execution happen simultaneously during the session, and results are not reliable predictors of remaining defect counts.',
  },
  {
    id: 28,
    domain: 'Chapter 4: Test Techniques',
    question: 'Which collaborative user story writing practice enables the team to achieve a collective understanding of what needs to be delivered?',
    options: [
      'Planning poker, so that a team can achieve consensus on the effort needed to implement a user story',
      'Reviews, so that a team can detect inconsistencies and contradictions in a user story',
      'Iteration planning, so that user stories with the highest business value for a customer can be prioritized for implementation',
      'Conversation, so that team members can understand how the software will be used',
    ],
    correctAnswer: 3,
    explanation: 'Conversation among team members explains how the software will be used, helping define meaningful acceptance criteria and a shared vision of what to deliver. Planning poker estimates effort, reviews detect issues, and iteration planning prioritizes work.',
  },
  {
    id: 29,
    domain: 'Chapter 4: Test Techniques',
    question: 'You have just started designing test cases for the following user story. As a customer, I want to be able to filter search results by price range, so that I can find products within my budget more easily. Acceptance criteria: 1. The filter should work for all versions of the application from version 3.0 upwards, 2. The filter should allow the customer to set a price range with a minimum and a maximum price, 3. The search results should update dynamically as the customer adjusts the price range filter. In all test cases the precondition is as follows: there are only two products available, products A and B. Product A costs $100 and product B costs $110. Which of the following is the BEST example of a test case for this user story?',
    options: [
      'Enter webpage and set filter to show prices between $90 and $100. Expected result: results show product A only. Set maximum price to $110. Expected result: results now include both products A and B',
      'Enter webpage. Expected result: the default minimum and maximum prices are $100 and $110 respectively. Add product C to stock, with price $120. Refresh the client webpage. Expected result: the default maximum price changes to $120',
      'Enter webpage and set filter to show prices between $90 and $115. Expected result: results show both products A and B. Change currency from USD to EUR. Expected result: the filter range changes correctly to EUR values, according to the current exchange rate',
      'Enter webpage with three different browsers: Edge, Chrome and Opera. In each browser set filter between $90 and $110. Expected result: results include both products A and B and the results layout is the same in all three browsers',
    ],
    correctAnswer: 0,
    explanation: 'This test case directly covers acceptance criteria 2 (set min/max price range) and 3 (results update dynamically when adjusting filter). The other options test unrelated features like default ranges, currency conversion, and cross-browser compatibility.',
  },
  {
    id: 30,
    domain: 'Chapter 5: Test Management',
    question: 'Which of the following BEST define EXIT criteria in a testing project?',
    options: [
      'Budget is approved',
      'Budget runs out',
      'Test basis is available',
      'Test cases achieved at least 80% statement coverage',
      'All test analysts are ISTQB certified at the Foundation Level',
    ],
    correctAnswer: [1, 3],
    correctAnswers: [1, 3],
    explanation: 'Running out of budget is a valid exit criterion (testing stops). Coverage measures like 80% statement coverage are typical exit criteria. Budget approval, test basis availability, and team certifications are entry criteria.',
  },
  {
    id: 31,
    domain: 'Chapter 5: Test Management',
    question: 'The team wants to estimate the time needed for one tester to execute four test cases for a software component. The team has gathered the following measures of the effort used to execute a single test case: Best-case scenario: 1 hour. Worst-case scenario: 8 hours. Most likely scenario: 3 hours. Given that the three-point estimation technique is being used, what is the final estimate of the time needed to execute all four test cases?',
    options: [
      '14 hours',
      '3.5 hours',
      '16 hours',
      '12 hours',
    ],
    correctAnswer: 0,
    explanation: 'Three-point estimate E = (a + 4m + b) / 6 = (1 + 12 + 8) / 6 = 3.5 hours per test case. For 4 test cases: 3.5 * 4 = 14 hours.',
  },
  {
    id: 32,
    domain: 'Chapter 5: Test Management',
    question: 'The table shows the traceability matrix from test cases to requirements. "X" means that a given test case covers the corresponding requirement. Req1 Req2 Req3 Req4 Req5 Req6 Req7. TC1 X X X X. TC2 X X X. TC3 X X. TC4 X. You want to prioritize the test cases following the additional coverage prioritization technique. You execute all four test cases. Which test case should be executed as the LAST one?',
    options: [
      'TC1',
      'TC2',
      'TC3',
      'TC4',
    ],
    correctAnswer: 1,
    explanation: 'TC1 (covers 4 reqs) runs first, then TC3 (covers 2 of the 3 remaining), then TC4 (covers the last one Req2). The remaining uncovered requirement coverage means TC2 is executed last, providing the least additional coverage at that point.',
  },
  {
    id: 33,
    domain: 'Chapter 5: Test Management',
    question: 'How can the testing quadrants be beneficial for testing?',
    options: [
      'They help in test planning by dividing the test process into four phases, corresponding to the four basic test levels: component, integration, system, and acceptance testing',
      'They help in assessing the high-level coverage (e.g., requirements coverage) based on low-level coverage (e.g., code coverage)',
      'They help non-technical stakeholders to understand the different test types and that some test types are more relevant to certain test levels than others',
      'They help agile teams to develop a communication strategy based on classifying people according to four basic psychological types, and on modelling the relations between them',
    ],
    correctAnswer: 2,
    explanation: 'Testing quadrants help stakeholders understand the relationships between test types, the activities they support (team support vs. product critique), and whether they are business- or technology-facing. They are not about test levels, coverage, or psychology.',
  },
  {
    id: 34,
    domain: 'Chapter 5: Test Management',
    question: 'For a given risk, its risk level is $1,000 and its risk likelihood is estimated as 50%. What is the risk impact?',
    options: [
      '$500',
      '$2,000',
      '$50,000',
      '$200',
    ],
    correctAnswer: 1,
    explanation: 'Risk level = Risk likelihood * Risk impact, so Risk impact = Risk level / Risk likelihood = $1,000 / 0.5 = $2,000.',
  },
  {
    id: 35,
    domain: 'Chapter 5: Test Management',
    question: 'Which of the following are product risks?',
    options: [
      'Scope creep',
      'Poor architecture',
      'Cost-cutting',
      'Poor tool support',
      'Too long response time',
    ],
    correctAnswer: [1, 4],
    correctAnswers: [1, 4],
    explanation: 'Product risks relate to product characteristics: poor architecture (option b) and too long response time (option e). Scope creep and cost-cutting are organizational project risks, and poor tool support is a technical project risk.',
  },
  {
    id: 36,
    domain: 'Chapter 5: Test Management',
    question: 'Which of the following is NOT a valid purpose for a test report?',
    options: [
      'Tracking test progress and identifying areas that require further attention',
      'Providing information on the tests executed, their results, and defects found',
      'Providing information about each defect, such as the steps to reproduce it',
      'Providing information on testing planned for the next period',
    ],
    correctAnswer: 2,
    explanation: 'Providing information about each defect (with reproduction steps) is the purpose of a defect report, not a test report. Test reports focus on test progress, summary of test activities, and future test plans.',
  },
  {
    id: 37,
    domain: 'Chapter 5: Test Management',
    question: 'The user reported a software failure. An engineer from the support team asked the user for the software version number where the failure was observed. Based on the version number, the team reassembled all the files that made up the release. This later allowed a developer to perform analysis, find the defect, and fix it. Which of the following enabled the above activity to be performed by the team?',
    options: [
      'Risk management',
      'Test monitoring and control',
      'Whole team approach',
      'Configuration management',
    ],
    correctAnswer: 3,
    explanation: 'Configuration management identifies, controls, and tracks work products. It keeps records of changed configuration items and allows reverting to previous baselines to reproduce previous test results.',
  },
  {
    id: 38,
    domain: 'Chapter 5: Test Management',
    question: 'Consider the following defect report for a Book Lending System. Defect ID: 001. Title: Unable to Return a Book. Severity: High. Priority: [empty]. Environment: Windows 10, Google Chrome. Description: When attempting to return a book using the Book Return feature, the system does not register the return and the book remains checked out to the user. Steps to Reproduce: Login to the Book Lending System as a user who has checked out a book. Click on the "Book Return" button for the book that has been checked out. System does not register the return and the book remains checked out. Expected Result: The book should be returned and no longer appear as checked out to the user. Actual Result: The book remains checked out to the user and is not registered as returned in the system. Attachments: [empty list]. Which of the following is MOST likely to help the developer reproduce the failure quickly?',
    options: [
      'Adding information about which users and which books the failure affects to the "Description" section',
      'Filling in the missing value for the "Priority" field',
      'Adding memory dumps and database snapshots taken after each step described in the "Steps to Reproduce" section to the "Attachments" section',
      'Repeating the same test case for different environments and writing defect reports for each of them separately',
    ],
    correctAnswer: 0,
    explanation: 'Adding information about which users and books the failure affects allows the developer to use the same input data and reproduce the failure quickly. Priority does not aid reproduction, and excessive attachments slow down analysis.',
  },
  {
    id: 39,
    domain: 'Chapter 6: Test Tools and Automation',
    question: 'Given the following test tool categories: (i) Collaboration tools, (ii) DevOps tools, (iii) Management tools, (iv) Non-functional testing tools, (v) Test design and implementation tools. Tools from which of the categories are MOST likely to facilitate test execution?',
    options: [
      'i, v',
      'ii, iv',
      'i, iii, v',
      'ii, iii, iv',
    ],
    correctAnswer: 1,
    explanation: 'DevOps tools support the delivery pipeline and CI/CD, which include test execution. Non-functional testing tools allow running tests that are difficult or impossible to perform manually. Collaboration, management, and test design tools do not directly facilitate execution.',
  },
  {
    id: 40,
    domain: 'Chapter 6: Test Tools and Automation',
    question: 'Which of the following is MOST likely to be a risk of test automation?',
    options: [
      'The detection of additional high-severity defects',
      'Providing measures that are too complicated for humans to derive',
      'Incompatibility with the development platform',
      'Substantially reduced test execution times',
    ],
    correctAnswer: 2,
    explanation: 'Incompatibility with the development platform is a real risk, as the automation would not be able to pass inputs to the test object or receive results. The other options are typically considered benefits of test automation.',
  },
];
