/**
 * ISTQB® Certified Tester Foundation Level (CTFL) v4.0.1
 * Practice Exam Questions - Sample Exam Set B
 *
 * Source: ISTQB_CTFL_v4.0_Sample-Exam-B v1.7 (April 1, 2025)
 * Copyright © International Software Testing Qualifications Board
 * Used with attribution under the ISTQB® copyright notice for non-commercial use.
 */

import type { ExamQuestion } from '@/types';

export const questions: ExamQuestion[] = [
  {
    id: 1,
    domain: 'Chapter 1: Fundamentals of Testing',
    question: 'Which of the following statements describe a valid test objective?',
    options: [
      'To prove that there are no unfixed defects in the system under test',
      'To prove that there will be no failures after the implementation of the system into production',
      'To reduce the risk level of the test object and to build confidence in the quality level',
      'To verify that there are no untested combinations of inputs',
    ],
    correctAnswer: 2,
    explanation: 'Testing is used to reduce the risk of defects and build confidence in the quality of the test object. Testing cannot prove absence of defects or guarantee no failures in production.',
  },
  {
    id: 2,
    domain: 'Chapter 1: Fundamentals of Testing',
    question: 'Which of the following options shows an example of test activities that contribute to success?',
    options: [
      'Having testers involved during various software development lifecycle (SDLC) activities will help to detect defects in work products',
      'Testers try not to disturb the developers while coding, so that the developers write better code',
      'Testers collaborating with end users help to improve the quality of defect reports during component integration and system testing',
      'Certified testers will design much better test cases than non-certified testers',
    ],
    correctAnswer: 0,
    explanation: 'Testers involved across SDLC activities detect defects in work products, contributing to testing success. The other options describe scenarios that do not represent testing best practices.',
  },
  {
    id: 3,
    domain: 'Chapter 1: Fundamentals of Testing',
    question: 'You have been assigned as a tester to a team producing a new system incrementally. You have noticed that no changes have been made to the existing regression test cases for several iterations and no new regression defects were identified. Your manager is happy, but you are not. Which testing principle explains your skepticism?',
    options: [
      'Tests wear out',
      'Absence-of-defects fallacy',
      'Defects cluster together',
      'Exhaustive testing is impossible',
    ],
    correctAnswer: 0,
    explanation: 'The "tests wear out" principle states that running the same tests repeatedly will eventually find no new defects, even though the system may still have undetected defects. Varying tests helps address this.',
  },
  {
    id: 4,
    domain: 'Chapter 1: Fundamentals of Testing',
    question: 'You work in a team that develops a mobile application for food ordering. In the current iteration the team decided to implement the payment functionality. Which of the following activities is a part of test analysis?',
    options: [
      'Estimating that testing the integration with the payment service will take 8 person-days',
      'Deciding that the team should test if it is possible to properly share payment between many users',
      'Using boundary value analysis (BVA) to derive the test data for the test cases that check the correct payment processing for the minimum allowed amount to be paid',
      'Analyzing the discrepancy between the actual result and expected result after executing a test case that checks the process of payment with a credit card, and reporting a defect',
    ],
    correctAnswer: 1,
    explanation: 'Test analysis involves evaluating the test basis and identifying test conditions. Deciding what to test is part of test analysis. Estimating is test planning, BVA is test design, and analyzing discrepancies is test completion.',
  },
  {
    id: 5,
    domain: 'Chapter 1: Fundamentals of Testing',
    question: 'Which of the following factors have a SIGNIFICANT influence on the test approach? (i) The SDLC, (ii) The number of defects detected in previous projects, (iii) The identified product risks, (iv) New regulatory requirements forcing formal white-box testing, (v) The test environment setup',
    options: [
      'i, ii have significant influence',
      'i, iii, iv have significant influence',
      'ii, iv, v have significant influence',
      'iii, v have significant influence',
    ],
    correctAnswer: 1,
    explanation: 'The SDLC (i), product risks (iii), and regulatory requirements (iv) significantly influence the test approach. The other factors (number of previous defects and test environment setup) are less direct influences.',
  },
  {
    id: 6,
    domain: 'Chapter 1: Fundamentals of Testing',
    question: 'Which TWO of the following tasks belong MAINLY to a testing role?',
    options: [
      'Configure test environments',
      'Maintain the product backlog',
      'Design solutions to new requirements',
      'Create the test plan',
      'Analyze the test basis',
    ],
    correctAnswer: [3, 4],
    correctAnswers: [3, 4],
    explanation: 'Creating the test plan and analyzing the test basis are main testing role tasks. Configuring test environments is a supporting task, and maintaining the product backlog and designing solutions are development tasks.',
  },
  {
    id: 7,
    domain: 'Chapter 1: Fundamentals of Testing',
    question: 'Which of the following skills (i-v) are the MOST important skills of a tester? (i) Having domain knowledge, (ii) Creating a product vision, (iii) Being a good team player, (iv) Planning and organizing the work of the team, (v) Critical thinking',
    options: [
      'ii and iv are important',
      'i, iii and v are important',
      'i, ii and v are important',
      'iii and iv are important',
    ],
    correctAnswer: 1,
    explanation: 'The most important tester skills are domain knowledge, being a good team player, and critical thinking. Product vision creation and team planning are typically management responsibilities.',
  },
  {
    id: 8,
    domain: 'Chapter 1: Fundamentals of Testing',
    question: 'How is the whole team approach present in the interactions between testers and business representatives?',
    options: [
      'Business representatives decide on test automation approaches',
      'Testers help business representatives to define a test strategy',
      'Business representatives are not part of the whole team approach',
      'Testers help business representatives to create suitable acceptance tests',
    ],
    correctAnswer: 3,
    explanation: 'Testers help business representatives create suitable acceptance tests as part of the whole team approach, which fosters collaboration and shared understanding.',
  },
  {
    id: 9,
    domain: 'Chapter 2: Testing Throughout the SDLC',
    question: 'Consider the following rule: "for every SDLC activity there is a corresponding test activity". In which SDLC models does this rule hold?',
    options: [
      'Only in sequential development models',
      'Only in iterative development models',
      'Only in iterative and incremental development models',
      'In sequential, incremental, and iterative development models',
    ],
    correctAnswer: 3,
    explanation: 'For every development activity there is a corresponding test activity, regardless of the SDLC model used — whether sequential, incremental, or iterative.',
  },
  {
    id: 10,
    domain: 'Chapter 2: Testing Throughout the SDLC',
    question: 'Which of the following statements BEST describes the acceptance test-driven development (ATDD) approach?',
    options: [
      'In ATDD, acceptance criteria are typically created based on the given/when/then format',
      'In ATDD, test cases are mainly created at component testing and are code-oriented',
      'In ATDD, tests are created based on acceptance criteria to drive the development of the related software',
      'In ATDD, tests are based on the desired behavior of the software, which makes it easier for team members to understand them',
    ],
    correctAnswer: 2,
    explanation: 'ATDD is a test-first approach where tests are derived from acceptance criteria to drive development. The tests are created before the code and serve as a definition of done.',
  },
  {
    id: 11,
    domain: 'Chapter 2: Testing Throughout the SDLC',
    question: 'Which of the following is NOT an example of the shift-left approach?',
    options: [
      'Reviewing the user requirements before they are formally accepted by the stakeholders',
      'Writing a component test before the corresponding code is written',
      'Executing a performance efficiency test for a component during component testing',
      'Writing a test script before setting up the configuration management process',
    ],
    correctAnswer: 3,
    explanation: 'Writing test scripts before setting up configuration management is not shift-left — configuration management should be set up first. The other options all describe moving testing activities earlier in the SDLC.',
  },
  {
    id: 12,
    domain: 'Chapter 2: Testing Throughout the SDLC',
    question: 'Which of the arguments below would you use to convince your manager to organize retrospectives at the end of each release cycle?',
    options: [
      'Retrospectives are very popular these days and clients would appreciate it if we added them to our processes',
      'Organizing retrospectives will save the organization money because without them end user representatives do not provide immediate feedback about the product',
      'Process weaknesses identified during the retrospective can be analyzed and serve as a to do list for the organization\'s continuous process improvement program',
      'Retrospectives embrace five values including courage and respect, which are crucial to maintain continuous improvement in the organization',
    ],
    correctAnswer: 2,
    explanation: 'Retrospectives identify process weaknesses that feed into the continuous process improvement program. The other options are either incorrect or describe unrelated concepts.',
  },
  {
    id: 13,
    domain: 'Chapter 2: Testing Throughout the SDLC',
    question: 'Which types of failures (1-4) fit which test levels (A-D) BEST? (1) Failures in system behavior as it deviates from the user\'s business needs, (2) Failures in communication between components, (3) Failures in logic in the code, (4) Failures in not correctly implemented business rules. (A) Component testing, (B) Component integration testing, (C) System testing, (D) Acceptance testing',
    options: [
      '1D, 2B, 3A, 4C',
      '1C, 2D, 3A, 4B',
      '1A, 2C, 3D, 4B',
      '1A, 2D, 3C, 4B',
    ],
    correctAnswer: 0,
    explanation: 'System behavior (1) is tested at acceptance testing (D), communication between components (2) at component integration (B), code logic (3) at component testing (A), and business rules (4) at system testing (C).',
  },
  {
    id: 14,
    domain: 'Chapter 2: Testing Throughout the SDLC',
    question: 'Which of the following statements is CORRECT?',
    options: [
      'Regression tests increase in number as the project progresses, whereas the number of confirmation tests decreases as the project progresses',
      'Regression tests are created and run when the test object is fixed, whereas confirmation tests are run whenever the test object is enhanced',
      'Regression testing is concerned with checking that the operational environment remains unchanged, whereas confirmation testing is concerned with testing changes to the test object',
      'Regression testing is concerned with adverse effects in unchanged code, whereas confirmation testing is concerned with testing changed code',
    ],
    correctAnswer: 3,
    explanation: 'Regression testing checks for adverse effects in unchanged code, while confirmation testing verifies that a specific defect fix in changed code works correctly.',
  },
  {
    id: 15,
    domain: 'Chapter 3: Static Testing',
    question: 'Which of the following is an example of a defect that can be found by static testing but NOT by dynamic testing?',
    options: [
      'Lack of usability provided through the user interface',
      'Code with no path that reaches it',
      'Poor response times for most of the expected users',
      'Required features that are not implemented in the code',
    ],
    correctAnswer: 1,
    explanation: 'Unreachable code can be found only by static analysis (code review or static analysis tools). Dynamic testing only executes reachable code and cannot find unreachable code without exhaustive input testing.',
  },
  {
    id: 16,
    domain: 'Chapter 3: Static Testing',
    question: 'Which of the following is a benefit of early and frequent stakeholder feedback?',
    options: [
      'Managers are aware of which developers are less productive',
      'It allows project managers to prioritize their stakeholder interactions',
      'It facilitates early communication of potential quality issues',
      'End users better understand why the delivery of the work product is delayed',
    ],
    correctAnswer: 2,
    explanation: 'Early and frequent stakeholder feedback facilitates early communication of potential quality issues, preventing misunderstandings and enabling timely corrections.',
  },
  {
    id: 17,
    domain: 'Chapter 3: Static Testing',
    question: 'Given the following task descriptions: (1) The quality characteristics to be evaluated and the exit criteria are selected, (2) Everyone has access to the work product, (3) Anomalies are identified in the work product, (4) Anomalies are discussed. And the following review activities: A. Individual review, B. Review initiation, C. Planning, D. Communication and analysis. Which of the following BEST matches the task descriptions and activities?',
    options: [
      '1B, 2C, 3D, 4A',
      '1B, 2D, 3C, 4A',
      '1C, 2A, 3B, 4D',
      '1C, 2B, 3A, 4D',
    ],
    correctAnswer: 3,
    explanation: 'The correct match is 1C (Planning: quality characteristics and exit criteria), 2B (Review initiation: access for everyone), 3A (Individual review: identifying anomalies), 4D (Communication and analysis: discussing anomalies).',
  },
  {
    id: 18,
    domain: 'Chapter 3: Static Testing',
    question: 'Given the following roles in reviews: (1) Scribe, (2) Review leader, (3) Facilitator, (4) Manager. And the following responsibilities: A. Ensures the effective running of review meetings and setting up a safe review environment, B. Records review information such as decisions and new anomalies, C. Decides what is to be reviewed and provides resources, D. Takes overall responsibility for the review such as organizing when and where it will take place. Which of the following BEST matches the roles and responsibilities?',
    options: [
      '1A, 2B, 3D, 4C',
      '1A, 2C, 3B, 4D',
      '1B, 2D, 3A, 4C',
      '1B, 2D, 3C, 4A',
    ],
    correctAnswer: 2,
    explanation: 'The correct match is 1B (Scribe: records review info), 2D (Review leader: organizes), 3A (Facilitator: ensures effective running), 4C (Manager: decides and provides resources).',
  },
  {
    id: 19,
    domain: 'Chapter 4: Test Techniques',
    question: 'Which of the following statements BEST describes the difference between decision table testing and branch testing?',
    options: [
      'In decision table testing, the test cases are derived from the decision statements in the code. In branch testing, the test cases are derived from knowledge of the control flow of the test object.',
      'In decision table testing, the test cases are derived from the specification that describes the business logic. In branch testing, the test cases are based on anticipation of potential defects in the source code.',
      'In decision table testing, the test cases are derived from knowledge of the control flow of the test object. In branch testing, test cases are derived from the specification that describes the business logic.',
      'In decision table testing, the test cases are independent of how the software is implemented. In branch testing, test cases can be created only after the design or implementation of the code.',
    ],
    correctAnswer: 3,
    explanation: 'Decision table testing is a black-box (specification-based) technique independent of implementation. Branch testing is a white-box (structure-based) technique requiring access to design or code.',
  },
  {
    id: 20,
    domain: 'Chapter 4: Test Techniques',
    question: 'Customers of the TestWash car wash chain have cards with a record of the number of washes they have bought so far. The initial value is 0. After entering the car wash, the system increases the number on the card by one. This value represents the number of the current wash. For every tenth wash the system gives a 10% discount, and for every twentieth wash, the system gives a further 40% discount (i.e., a 50% discount in total). Which of the following sets of input data (understood as the numbers of the current wash) achieves the highest equivalence partition coverage?',
    options: [
      '19, 20, 30',
      '11, 12, 20',
      '1, 10, 50',
      '10, 29, 30, 31',
    ],
    correctAnswer: 0,
    explanation: 'Set 19, 20, 30 covers all three valid equivalence partitions: 19 (no discount), 20 (50% discount), and 30 (10% discount), achieving the highest partition coverage.',
  },
  {
    id: 21,
    domain: 'Chapter 4: Test Techniques',
    question: 'You are testing a form that verifies the correctness of the length of the password given as input. The form accepts a password with the correct length and rejects a password that is too short or too long. The password length is correct if it has between 6 and 12 characters inclusive. At first, the form is empty (password length = 0). You apply boundary value analysis to the "password length" variable. Your set of test cases achieves 100% 2-value boundary value coverage. The team decided that due to the high risk of this component, test cases should be added to ensure 100% 3-value boundary value coverage. Which additional password lengths should be tested to achieve this?',
    options: [
      '4, 5, 13, 14',
      '7, 11',
      '1, 5, 13',
      '1, 4, 7, 11, 14',
    ],
    correctAnswer: 3,
    explanation: 'For full 3-value BVA, values 0, 1, 4, 5, 6, 7, 11, 12, 13, 14 must be tested. Since 2-value BVA covers 0, 5, 6, 12, 13, the additional lengths needed are 1, 4, 7, 11, and 14.',
  },
  {
    id: 22,
    domain: 'Chapter 4: Test Techniques',
    question: 'The following decision table contains the rules for determining the risk of atherosclerosis. (Conditions: Cholesterol in mg/dl: <=124, 125-200, >=201; Blood pressure in mm Hg: <=140, >140; Actions: Risk level very low, low, medium, high, very high across 5 rules). You designed the test cases with the following input data: TC1: Cholesterol=125, Blood pressure=141; TC2: Cholesterol=200, Blood pressure=201; TC3: Cholesterol=124, Blood pressure=201; TC4: Cholesterol=109, Blood pressure=200; TC5: Cholesterol=201, Blood pressure=140. What is the decision table coverage achieved by these test cases?',
    options: [
      '40%',
      '60%',
      '80%',
      '100%',
    ],
    correctAnswer: 1,
    explanation: 'TC1 and TC2 both cover Rule 4, TC3 and TC4 both cover Rule 2, and TC5 covers Rule 5. Three out of five rules are covered, achieving 3/5 = 60% decision table coverage.',
  },
  {
    id: 23,
    domain: 'Chapter 4: Test Techniques',
    question: 'A storage system can store up to three elements and is modeled by a state transition diagram. The variable N represents the number of currently stored elements. Which of the following test cases, represented as sequences of events, achieves the highest level of valid transitions coverage?',
    options: [
      'Add, Remove, Add, Add, Add',
      'Add, Add, Add, Add, Remove, Remove',
      'Add, Add, Add, Remove, Remove',
      'Add, Add, Add, Remove, Add',
    ],
    correctAnswer: 2,
    explanation: 'Test c) Add, Add, Add, Remove, Remove covers all 5 valid transitions of the state diagram, achieving 100% valid transitions coverage. The other tests achieve only 80% or less.',
  },
  {
    id: 24,
    domain: 'Chapter 4: Test Techniques',
    question: 'You run two test cases, T1 and T2, on the same code. Test T1 achieved 40% statement coverage and test T2 achieved 65% statement coverage. Which of the following sentences must be necessarily true?',
    options: [
      'The test suite composed of tests T1 and T2 achieves 105% statement coverage',
      'There exists at least one statement that must have been executed by both T1 and T2',
      'At least 5% of the statements in the code that was tested are non-executable',
      'The test suite composed of tests T1 and T2 achieves full branch coverage',
    ],
    correctAnswer: 1,
    explanation: 'If the statements executed by T1 and T2 were disjoint, the combined coverage would be 105%, which is impossible. Therefore, at least 5% of executable statements must have been executed by both tests.',
  },
  {
    id: 25,
    domain: 'Chapter 4: Test Techniques',
    question: 'Let the branch coverage metric be defined as BCov = (X / Y) * 100%. What do X and Y represent in this formula?',
    options: [
      'X = number of decision outcomes exercised by the test cases; Y = total number of decision outcomes in the code',
      'X = number of conditional branches exercised by the test cases; Y = total number of branches in the code',
      'X = number of branches exercised by the test cases; Y = total number of branches in the code',
      'X = number of conditional branches exercised by the test cases; Y = total number of decision outcomes in the code',
    ],
    correctAnswer: 2,
    explanation: 'Branch coverage is measured as the number of branches exercised by the test cases (both conditional and unconditional) divided by the total number of branches in the code.',
  },
  {
    id: 26,
    domain: 'Chapter 4: Test Techniques',
    question: 'Which TWO of the following statements provide the BEST rationale for using exploratory testing?',
    options: [
      'Testers have not been allocated enough time for test design and test execution',
      'The existing test strategy requires that testers use formal, black-box test techniques',
      'The specification is written in a formal language that can be processed by a tool',
      'Testers are the members of an agile team and have good programming skills',
      'Testers are experienced in the business domain and have good analytical skills',
    ],
    correctAnswer: [0, 4],
    correctAnswers: [0, 4],
    explanation: 'Exploratory testing is useful when there are few or inadequate specifications or significant time pressure. It is also more effective when testers are experienced, have domain knowledge, and possess strong analytical skills.',
  },
  {
    id: 27,
    domain: 'Chapter 4: Test Techniques',
    question: 'Which of the following BEST fits as an element of the checklist used in checklist-based testing?',
    options: [
      'The developer made an error when implementing the code',
      'The achieved statement coverage exceeds 85%',
      'The program works correctly regarding functional and non-functional requirements',
      'The error messages are written in language that the user can understand',
    ],
    correctAnswer: 3,
    explanation: 'A good checklist contains test conditions to be verified, such as "error messages are written in language the user can understand." Other options are too general, are exit criteria, or describe errors rather than test conditions.',
  },
  {
    id: 28,
    domain: 'Chapter 4: Test Techniques',
    question: 'Consider the following acceptance criteria for a user story written from the perspective of an online store owner: "Given that the user is logged in and on the homepage, When the user clicks on the \'Add Item\' button, Then the \'Create Item\' form should appear, And the user should be able to input a name and price for the new item." In what format is this acceptance criteria written?',
    options: [
      'Rule-oriented',
      'Scenario-oriented',
      'Product-oriented',
      'Process-oriented',
    ],
    correctAnswer: 1,
    explanation: 'This is a Given/When/Then format, which is a scenario-oriented format because it describes a scenario to be verified rather than rules to be followed.',
  },
  {
    id: 29,
    domain: 'Chapter 4: Test Techniques',
    question: 'Your team analyzes the following user story in order to define the acceptance criteria: "As a registered customer, I want to be able to view my previous orders on the company\'s website, so that I can keep track of my purchases." Which of the following test cases will NOT be relevant for this user story?',
    options: [
      'Input: the customer logs into their account on the website and clicks the "see order history" button. Expected result: the system shows a list of all the customer\'s previous orders, including the date, order number, and total cost',
      'Input: the customer clicks on an order from the order list. Expected result: the system displays the individual items purchased, along with their prices and quantities',
      'Input: the customer clicks "Sort ascending" button on the order history screen. Expected result: the system shows the order history sorted by order number in ascending order',
      'Input: an unregistered customer registers as a new customer with a valid e-mail address that does not already exist in the customer database. Expected result: the system accepts the registration and creates the account',
    ],
    correctAnswer: 3,
    explanation: 'Test case d) relates to customer registration, which is not part of this user story. The user story is specifically about viewing previous orders, not registration.',
  },
  {
    id: 30,
    domain: 'Chapter 5: Test Management',
    question: 'Your team follows the process that uses the DevOps delivery pipeline. The first three steps of this process are: (1) Code development, (2) Submit code into a version control system and merge it into the "test" branch, (3) Perform component testing for the submitted code. Which of the following is BEST suited to be the entry criterion for step (2) of this pipeline?',
    options: [
      'Static analysis returns no high severity warnings for the submitted code',
      'System version control reports no conflicts when merging code into the "test" branch',
      'Component tests are compiled and ready to be executed',
      'Statement coverage is at least 80%',
    ],
    correctAnswer: 0,
    explanation: 'Static analysis with no high severity warnings should be checked before code submission. The other options are checked after submission or are entry/exit criteria for later steps.',
  },
  {
    id: 31,
    domain: 'Chapter 5: Test Management',
    question: 'You want to estimate the test effort for the new project using estimation based on ratios. You calculate the test-to-development effort ratio using averaged data from four historical projects: P1 (Dev: $800,000, Test: $40,000), P2 (Dev: $1,200,000, Test: $130,000), P3 (Dev: $600,000, Test: $70,000), P4 (Dev: $1,000,000, Test: $120,000). The estimated development effort for the new project is $800,000. What is your estimate of the test effort?',
    options: [
      '$40,000',
      '$80,000',
      '$81,250',
      '$82,500',
    ],
    correctAnswer: 1,
    explanation: 'The average test effort is $90,000, giving a 1:10 test-to-development ratio. 10% of $800,000 = $80,000.',
  },
  {
    id: 32,
    domain: 'Chapter 5: Test Management',
    question: 'You are testing a web application that allows users to SEARCH for products, VIEW product details, ADD products to a shopping cart, and place an ORDER. You have prepared seven test cases (TC1 SEARCH product A priority 4; TC2 SEARCH product B priority 4; TC3 VIEW product A priority 3; TC4 VIEW product B priority 2; TC5 ADD product A priority 3; TC6 ADD product B priority 1; TC7 place ORDER priority 5). Dependencies: SEARCH must be tested before VIEW, VIEW before ADD, ADD before ORDER. Which test case should be executed as the fourth one?',
    options: [
      'TC3',
      'TC1',
      'TC7',
      'TC2',
    ],
    correctAnswer: 1,
    explanation: 'The optimal order respecting dependencies and priorities is TC2 -> TC4 -> TC6 -> TC1 -> TC3 -> TC5 -> TC7. TC1 is fourth.',
  },
  {
    id: 33,
    domain: 'Chapter 5: Test Management',
    question: 'According to the testing quadrants model, which of the following falls into quadrant Q1 ("technology facing" and "support the team")?',
    options: [
      'Usability testing',
      'Functional testing',
      'User acceptance testing',
      'Component integration testing',
    ],
    correctAnswer: 3,
    explanation: 'Component integration testing is technology-facing testing that supports the team, placing it in quadrant Q1. Usability, functional, and user acceptance testing are business-facing tests in other quadrants.',
  },
  {
    id: 34,
    domain: 'Chapter 5: Test Management',
    question: 'Given the following risks: (1) Ineffective loop implementation causes long system responses, (2) Consumers change their preferences, (3) Flooding of the server room, (4) Patients above a certain age receive inaccurate reports. And the following mitigation activities: A. Risk acceptance, B. Testing for performance efficiency, C. Using boundary value analysis, D. Risk transfer. Which of the following BEST matches the risks with the mitigation activities?',
    options: [
      '1C, 2D, 3A, 4B',
      '1B, 2D, 3A, 4C',
      '1B, 2A, 3D, 4C',
      '1C, 2A, 3D, 4B',
    ],
    correctAnswer: 2,
    explanation: 'Long system responses need performance testing (1B), consumer preference changes are usually accepted (2A), server room flooding is transferred via insurance (3D), and patient age boundary issues benefit from BVA (4C).',
  },
  {
    id: 35,
    domain: 'Chapter 5: Test Management',
    question: 'Which of the following is a product quality metric?',
    options: [
      'Mean time to failure',
      'Number of defects found',
      'Requirements coverage',
      'Defect detection percentage',
    ],
    correctAnswer: 0,
    explanation: 'Mean time to failure measures the maturity quality characteristic, making it a product quality metric. The other options are examples of defect or coverage metrics, not product quality metrics.',
  },
  {
    id: 36,
    domain: 'Chapter 5: Test Management',
    question: 'You are a member of a test team located in North America, developing a product for a client located in Europe. The team is agile and follows the DevOps approach and uses a continuous integration/continuous delivery pipeline. Which of the following is the LEAST effective way to communicate test progress to the customer?',
    options: [
      'Face-to-face',
      'Dashboards',
      'Email',
      'Video conferencing',
    ],
    correctAnswer: 0,
    explanation: 'The client is in a different location and time zone, making face-to-face communication difficult. Dashboards, email, and video conferencing are more effective in this distributed context.',
  },
  {
    id: 37,
    domain: 'Chapter 5: Test Management',
    question: 'Which of the following BEST describes an example of how configuration management (CM) supports testing?',
    options: [
      'Having the version number of the environment, the CM tool can retrieve the version numbers of libraries, stubs and drivers used in that environment',
      'Having a record of the values of the inputs, the CM tool can execute the test cases for these configurations and calculate the coverage',
      'Having data about the date of purchase of a software license, the CM tool automatically generates information about the fact that the product license is coming to an end',
      'Having the version number of the test case, the CM tool can automatically generate test data for this test case',
    ],
    correctAnswer: 0,
    explanation: 'For complex configuration items like a test environment, CM records the items it consists of, their relationships, and versions, enabling retrieval of version numbers of libraries, stubs, and drivers.',
  },
  {
    id: 38,
    domain: 'Chapter 5: Test Management',
    question: 'You are testing a sort function that gets a set of numbers as input and returns the same set of numbers sorted in ascending order. The test log shows: TC1 (Input: 3 -> Output: 3) passed; TC2 (Input: 3 11 6 5 -> Output: 3 5 6 11) passed; TC3 (Input: 8 7 3 7 1 -> Output: 1 3 7 8) failed; TC4 (Input: -2 -2 -2 -3 -3 -> Output: -3 -2) failed; TC5 (Input: 0 -2 0 3 4 4 -> Output: -2 0 3 4) failed. Which of the following provides the BEST description of the failure that can be used in a defect report?',
    options: [
      'The system fails to sort several sets of numbers. Reference: TC3, TC4, TC5.',
      'The system seems to disregard duplicates while sorting. Reference: TC3, TC4, TC5.',
      'The system fails to sort negative numbers. Reference: TC4, TC5.',
      'TC3, TC4 and TC5 have defects (duplicate input data) and should be corrected.',
    ],
    correctAnswer: 1,
    explanation: 'From the test results, the system appears to ignore duplicates and sort the list disregarding repetitions, explaining the failures in TC3, TC4, and TC5.',
  },
  {
    id: 39,
    domain: 'Chapter 6: Test Tools and Automation',
    question: 'Given the following descriptions: (1) Support workflow tracking, (2) Facilitate communication, (3) Virtual machines, (4) Support reviews. And the following test tool categories: A. Static testing tools, B. Tools supporting scalability and deployment standardization, C. DevOps tools, D. Collaboration tools. Which of the following BEST matches the descriptions and categories?',
    options: [
      '1A, 2B, 3C, 4D',
      '1B, 2D, 3C, 4A',
      '1C, 2D, 3B, 4A',
      '1D, 2C, 3A, 4B',
    ],
    correctAnswer: 2,
    explanation: 'The correct match is 1C (DevOps tools support workflow tracking), 2D (Collaboration tools facilitate communication), 3B (Scalability/deployment tools use virtual machines), 4A (Static testing tools support reviews).',
  },
  {
    id: 40,
    domain: 'Chapter 6: Test Tools and Automation',
    question: 'Which of the following is MOST likely to be a benefit of test automation?',
    options: [
      'It provides coverage measures that are too complicated for humans to derive',
      'It shares responsibility for the testing with the tool vendor',
      'It removes the need for critical thinking when analyzing test results',
      'It generates test cases from an analysis of the program code',
    ],
    correctAnswer: 0,
    explanation: 'Test automation can provide coverage measures too complicated for humans to derive, such as white-box testing coverage for non-trivial code. The other options are misconceptions about test automation benefits.',
  },
];
