/**
 * ISTQB® Certified Tester Foundation Level (CTFL) v4.0.1
 * Practice Exam Questions - Sample Exam Set C
 *
 * Source: ISTQB_CTFL_v4.0_Sample-Exam-C v1.6
 * Copyright © International Software Testing Qualifications Board
 * Used with attribution under the ISTQB® copyright notice for non-commercial use.
 */

import type { ExamQuestion } from '@/types';

export const questions: ExamQuestion[] = [
  {
    id: 1,
    domain: 'Chapter 1: Fundamentals of Testing',
    question: 'Which of the following is a typical test objective?',
    options: [
      'Validating that documented requirements are met',
      'Causing failures and identifying defects',
      'Initiating errors and identifying root causes',
      'Verifying the test object meets user expectations',
    ],
    correctAnswer: 1,
    explanation: 'Causing failures and identifying defects is the most common objective of dynamic testing. The other options confuse validation with verification, or describe debugging rather than testing.',
  },
  {
    id: 2,
    domain: 'Chapter 1: Fundamentals of Testing',
    question: 'Which of the following statements BEST describes the difference between testing and debugging?',
    options: [
      'Testing causes failures while debugging fixes failures',
      'Testing is a negative activity while debugging is a positive activity',
      'Testing determines that defects exist while debugging removes defects',
      'Testing finds the cause of defects while debugging fixes the cause of defects',
    ],
    correctAnswer: 2,
    explanation: 'Testing determines that defects exist (via reviews or by causing failures) while debugging is a separate developer activity that locates and removes those defects.',
  },
  {
    id: 3,
    domain: 'Chapter 1: Fundamentals of Testing',
    question: 'The "absence-of-defects fallacy" is one of the principles of testing. Which of the following is an example of addressing this principle in practice?',
    options: [
      'Explaining that it is not possible for testing to show the absence of defects',
      'Supporting the end users to perform acceptance testing',
      'Ensuring that no implementation defects remain in the delivered system',
      'Modifying tests that cause no failures to ensure few defects remain',
    ],
    correctAnswer: 1,
    explanation: 'The absence-of-defects fallacy states that verifying correctness does not guarantee user satisfaction, so supporting end users to perform acceptance testing validates that the system meets user needs.',
  },
  {
    id: 4,
    domain: 'Chapter 1: Fundamentals of Testing',
    question: 'Which of the following test activities are MOST likely to involve the application of boundary value analysis and equivalence partitioning?',
    options: [
      'Test implementation',
      'Test design',
      'Test execution',
      'Test monitoring',
      'Test analysis',
    ],
    correctAnswer: [1, 4],
    correctAnswers: [1, 4],
    explanation: 'Boundary value analysis and equivalence partitioning are test techniques used in test design (to create test cases from coverage items) and in test analysis (to identify test conditions).',
  },
  {
    id: 5,
    domain: 'Chapter 1: Fundamentals of Testing',
    question: 'Given the following testware: (1) Coverage items, (2) Change requests, (3) Test execution schedule, (4) Prioritized test conditions. And the following test activities: A. Test analysis, B. Test design, C. Test implementation, D. Test completion. Which of the following BEST shows the testware produced by the activities?',
    options: [
      '1B, 2D, 3C, 4A',
      '1B, 2D, 3A, 4C',
      '1D, 2C, 3A, 4B',
      '1D, 2C, 3B, 4A',
    ],
    correctAnswer: 0,
    explanation: 'Test design produces coverage items (1B), test completion produces change requests (2D), test implementation produces the execution schedule (3C), and test analysis produces prioritized test conditions (4A).',
  },
  {
    id: 6,
    domain: 'Chapter 1: Fundamentals of Testing',
    question: 'Which of the following statements about the different testing roles is MOST likely to be CORRECT?',
    options: [
      'In Agile software development, the test management role is the primary responsibility of the team, while the testing role is primarily the responsibility of a single individual from outside the team',
      'The testing role is primarily responsible for test monitoring and test control, while the test management role is primarily responsible for test planning and test completion',
      'In Agile software development, test management activities that span multiple teams are handled by a test manager outside the team, while some test management tasks are handled by the team itself',
      'The test management role is primarily responsible for test analysis and test design, while the testing role is primarily responsible for test implementation and test execution',
    ],
    correctAnswer: 2,
    explanation: 'In Agile, some test management tasks are handled by the team itself, while cross-team test management activities are typically handled by a test manager outside the team.',
  },
  {
    id: 7,
    domain: 'Chapter 1: Fundamentals of Testing',
    question: 'Which of the following is an advantage of the whole-team approach?',
    options: [
      'Teams with no testers',
      'Improved team dynamics',
      'Specialist team members',
      'Larger team sizes',
    ],
    correctAnswer: 1,
    explanation: 'The whole-team approach leverages diverse skill sets effectively, fostering superior team dynamics, robust communication, collaboration, and a synergistic effect.',
  },
  {
    id: 8,
    domain: 'Chapter 1: Fundamentals of Testing',
    question: 'Which of the following statements about the independence of testing is CORRECT?',
    options: [
      'Independent testers will find defects due to their different technical perspective from developers, but their independence may lead to an adversarial relationship with the developers',
      'Developers\' familiarity with their own code means they only find a few defects in it, however their shared software background with testers means these defects would also be found by the testers',
      'Independent testing requires testers who are outside the developer\'s team and ideally from outside the organization, however these testers find it difficult to understand the application domain',
      'Testers from outside the developer\'s team are more independent than testers from within the team, but the testers from within the team are more likely to be blamed for delays in product release',
    ],
    correctAnswer: 0,
    explanation: 'Independent testers identify different defects due to varied backgrounds, but a downside is potential isolation from the development team, which can lead to an adversarial relationship and blame for delays.',
  },
  {
    id: 9,
    domain: 'Chapter 2: Testing Throughout the SDLC',
    question: 'Which of the following is a good testing practice that applies to all software development lifecycles?',
    options: [
      'For each test level, there is a corresponding development level',
      'For each test objective, there is a corresponding development objective',
      'For every test activity, there is a corresponding user activity',
      'For every development activity, there is a corresponding test activity',
    ],
    correctAnswer: 3,
    explanation: 'Quality control applies to all development activities, meaning every software development activity has a corresponding test activity regardless of the SDLC used.',
  },
  {
    id: 10,
    domain: 'Chapter 2: Testing Throughout the SDLC',
    question: 'Which of the following is an example of a test-first approach to development?',
    options: [
      'Component Test-Driven Development',
      'Integration Test-Driven Development',
      'System Test-Driven Development',
      'Acceptance Test-Driven Development',
    ],
    correctAnswer: 3,
    explanation: 'Acceptance Test-Driven Development (ATDD) is a well-known test-first approach where tests are defined and agreed upon with business stakeholders before the code is written.',
  },
  {
    id: 11,
    domain: 'Chapter 2: Testing Throughout the SDLC',
    question: 'Which of the following provides the BEST description of shift-left?',
    options: [
      'When agreed by the developers, manual activities on the left-hand side of the test process are automated to support the principle of "early testing saves time and money"',
      'Where cost-effective, test activities are moved earlier in the software development lifecycle (SDLC) to reduce the total cost of quality by reducing the number of defects found later in the SDLC',
      'When they have spare time available, testers are required to automate tests for regression testing, starting with component tests and component integration tests',
      'When available, testers are trained to perform tasks early in the SDLC to allow more test activities to be automated later in the SDLC',
    ],
    correctAnswer: 1,
    explanation: 'Shift-left emphasizes moving test activities earlier in the SDLC where cost-effective, reducing total cost of quality by catching defects earlier.',
  },
  {
    id: 12,
    domain: 'Chapter 2: Testing Throughout the SDLC',
    question: 'Which of the following is LEAST likely to occur as a result of a retrospective?',
    options: [
      'The quality of future test objects improves by identifying improvements in development practices',
      'Test efficiency improves by speeding up the configuration of test environments through automation',
      'End users\' understanding of the development and test processes is improved',
      'Automated test scripts are enhanced through feedback from developers',
    ],
    correctAnswer: 2,
    explanation: 'Retrospectives typically include testers, developers, architects, product owners, and business analysts, but end users are rarely invited, so their understanding of dev/test processes is unlikely to improve.',
  },
  {
    id: 13,
    domain: 'Chapter 2: Testing Throughout the SDLC',
    question: 'Which of the following test levels is MOST likely being performed if the testing is focused on validation and is not being performed by testers?',
    options: [
      'Component testing',
      'Component integration testing',
      'System integration testing',
      'Acceptance testing',
    ],
    correctAnswer: 3,
    explanation: 'Acceptance testing focuses on validating the system meets user business needs and is ideally performed by end users rather than dedicated testers.',
  },
  {
    id: 14,
    domain: 'Chapter 2: Testing Throughout the SDLC',
    question: 'The navigation system software has been updated due to it suggesting routes that break traffic laws, such as driving the wrong way down one-way streets. Which of the following BEST describes the testing that will be performed?',
    options: [
      'Only confirmation testing',
      'Confirmation testing then regression testing',
      'Only regression testing',
      'Regression testing then confirmation testing',
    ],
    correctAnswer: 1,
    explanation: 'Confirmation testing first verifies the fix for the traffic law defect works correctly, then regression testing ensures the update has not introduced or uncovered defects elsewhere.',
  },
  {
    id: 15,
    domain: 'Chapter 3: Static Testing',
    question: 'Given the following example defects: (i) Two different parts of the design specification disagree due to the complexity of the design, (ii) A response time is too long and so makes users lose patience, (iii) A path in the code cannot be reached during execution, (iv) A variable is declared but never subsequently used in the program, (v) The amount of memory needed by the program to generate a report is too high. Which of the following BEST identifies example defects that could be found by static testing (rather than dynamic testing)?',
    options: [
      'ii, v',
      'iii, v',
      'i, ii, iv',
      'i, iii, iv',
    ],
    correctAnswer: 3,
    explanation: 'Static testing most easily finds specification defects (i), and coding defects like unreachable code (iii) and unused variables (iv). Response time (ii) and memory (v) require execution to detect.',
  },
  {
    id: 16,
    domain: 'Chapter 3: Static Testing',
    question: 'Which of the following is a benefit of early and frequent stakeholder feedback?',
    options: [
      'Changes to requirements are understood and implemented earlier',
      'It ensures business stakeholders understand user requirements',
      'It allows product owners to change their requirements as often as they want',
      'End users are told which requirements will not be implemented prior to release',
    ],
    correctAnswer: 0,
    explanation: 'Early and frequent stakeholder feedback facilitates early communication of issues, prevents requirement misunderstandings, and ensures changes in stakeholder requirements are understood and implemented sooner.',
  },
  {
    id: 17,
    domain: 'Chapter 3: Static Testing',
    question: 'Given the following review types: (1) Technical review, (2) Informal review, (3) Inspection, (4) Walkthrough. And the following descriptions: A. Includes objectives such as gaining consensus, generating new ideas, and motivating authors to improve. B. Includes objectives such as educating reviewers, gaining consensus, generating new ideas and detecting potential defects. C. The main objective is detecting potential defects and it requires metrics collection to support process improvement. D. The main objective is detecting potential defects and it generates no formal documented output. Which of the following BEST matches the review types and the descriptions?',
    options: [
      '1A, 2B, 3C, 4D',
      '1A, 2D, 3C, 4B',
      '1B, 2C, 3D, 4A',
      '1C, 2D, 3A, 4B',
    ],
    correctAnswer: 1,
    explanation: 'Technical review matches A (gaining consensus, new ideas, motivating), informal review matches D (no formal documented output), inspection matches C (metrics collection), and walkthrough matches B (educating reviewers).',
  },
  {
    id: 18,
    domain: 'Chapter 3: Static Testing',
    question: 'Which of the following is a factor that contributes to a successful review?',
    options: [
      'Ensure management participate as reviewers',
      'Split large work products into smaller parts',
      'Set reviewer evaluation as an objective',
      'Plan to cover one document per review',
    ],
    correctAnswer: 1,
    explanation: 'To ensure successful reviews, work products should be broken into small enough parts to be reviewed in a reasonable timescale, preventing reviewers from losing focus.',
  },
  {
    id: 19,
    domain: 'Chapter 4: Test Techniques',
    question: 'What is the MAIN difference between black-box test techniques and experience-based test techniques?',
    options: [
      'The test object',
      'The test level at which the test technique is used',
      'The test basis',
      'The software development lifecycle (SDLC) in which the test technique can be used',
    ],
    correctAnswer: 2,
    explanation: 'Black-box (specification-based) techniques rely on a specification as the test basis, whereas experience-based techniques rely on the tester\'s knowledge and experience and may not use the specification at all.',
  },
  {
    id: 20,
    domain: 'Chapter 4: Test Techniques',
    question: 'You are testing a PIN validator, which accepts valid PINs and rejects invalid PINs. A PIN is a sequence of digits. A PIN is valid if it consists of four digits, which are not all the same digit. You have identified the following valid equivalence partitions: Variable: PIN code length - the partition "length correct" (four-digit PINs) and the partition "length incorrect" (PINs with length other than 4). Variable: Number of different digits - the partition "number of different digits correct" (PINs with at least two different digits) and the partition "number of different digits incorrect" (PINs with all digits being the same). Which of the following is the BEST set of input test data to cover the identified equivalence partitions?',
    options: [
      '12, 1111, 1234, 12345',
      '1, 123, 1111, 1234',
      '11, 12, 1111, 12345',
      '123, 1222, 12345',
    ],
    correctAnswer: 0,
    explanation: '12 covers length incorrect (too few), 1111 covers length correct with same digits, 1234 covers length correct with different digits, and 12345 covers length incorrect (too many), thus covering all four partitions.',
  },
  {
    id: 21,
    domain: 'Chapter 4: Test Techniques',
    question: 'A developer was asked to implement the following business rule: INPUT: value (integer number). IF (value <= 100 OR value >= 200) THEN write "value incorrect" ELSE write "value OK". You design the test cases using 2-value boundary value analysis. Which of the following sets of test inputs achieves the greatest coverage?',
    options: [
      '100, 150, 200, 201',
      '99, 100, 200, 201',
      '98, 99, 100, 101',
      '101, 150, 199, 200',
    ],
    correctAnswer: 3,
    explanation: 'The boundaries are 100, 101, 199, and 200. Option d includes 101, 199, and 200, achieving 75% coverage, the highest of the given sets.',
  },
  {
    id: 22,
    domain: 'Chapter 4: Test Techniques',
    question: 'You are working on a project to develop a system to analyze driving test results. You have been asked to design test cases based on the following decision table. R1: First attempt? - - F; Theoretical passed? T F -; Practical passed? T - F; Action: Issue license? X (blank) (blank); Request additional lessons? (blank) X (blank); Request retake? (blank) X. What test data will show that there are contradictory rules in the decision table?',
    options: [
      'C1 = T, C2 = T, C3 = F',
      'C1 = T, C2 = F, C3 = T',
      'C1 = T, C2 = T, C3 = T and C1 = F, C2 = T, C3 = T',
      'C1 = F, C2 = F, C3 = F',
    ],
    correctAnswer: 3,
    explanation: 'The combination (F, F, F) matches both R2 and R3, but R2 and R3 specify different actions (additional lessons vs. retake exam), revealing a contradiction between these two rules.',
  },
  {
    id: 23,
    domain: 'Chapter 4: Test Techniques',
    question: 'You are designing test cases based on the following state transition diagram. What is the MINIMUM number of test cases required to achieve 100% valid transitions coverage?',
    options: [
      '3',
      '2',
      '5',
      '6',
    ],
    correctAnswer: 0,
    explanation: 'Three transitions (REQUESTING→CONFIRMED, WAITING LIST→CONFIRMED, WAITING LIST→END) cannot appear in the same test case, requiring at least three test cases to cover all valid transitions.',
  },
  {
    id: 24,
    domain: 'Chapter 4: Test Techniques',
    question: 'You want to apply branch testing to the code represented by the following control flow graph. How many coverage items do you need to test?',
    options: [
      '2',
      '4',
      '8',
      '7',
    ],
    correctAnswer: 2,
    explanation: 'In branch testing, the coverage items are the branches (edges) of the control flow graph, of which there are 8 in the diagram.',
  },
  {
    id: 25,
    domain: 'Chapter 4: Test Techniques',
    question: 'How can white-box testing be useful in support of black-box testing?',
    options: [
      'White-box coverage measures can help testers evaluate black-box tests in terms of the code coverage achieved by these black-box tests',
      'White-box coverage analysis can help testers identify unreachable fragments of the source code',
      'Branch testing subsumes black-box test techniques, so achieving full branch coverage guarantees achieving full coverage of any black-box technique',
      'White-box test techniques can provide coverage items for black-box techniques',
    ],
    correctAnswer: 0,
    explanation: 'White-box coverage measures provide an objective measure of code coverage, helping testers evaluate their black-box tests and generate additional tests where coverage is lacking.',
  },
  {
    id: 26,
    domain: 'Chapter 4: Test Techniques',
    question: 'Consider the following list: Correct input not accepted, Incorrect input accepted, Wrong output format, Division by zero. What test technique is MOST PROBABLY used by the tester who uses this list when performing testing?',
    options: [
      'Exploratory testing',
      'Fault attack',
      'Checklist-based testing',
      'Boundary value analysis',
    ],
    correctAnswer: 1,
    explanation: 'The list represents possible errors, defects, and failures, which is the hallmark of a fault attack, a methodical approach to error guessing.',
  },
  {
    id: 27,
    domain: 'Chapter 4: Test Techniques',
    question: 'Which of the following BEST describes how using checklist-based testing can result in increased coverage?',
    options: [
      'Checklist items can be defined at a sufficiently low level of detail, so the tester can implement and execute detailed test cases based on these items',
      'Checklists can be automated, so each time an automated test execution covers the checklist items, it results in additional coverage',
      'Each checklist item should be tested separately and independently, so the elements cover different areas of the software',
      'Two testers designing and executing tests based on the same high-level checklist items will typically perform the testing in slightly different ways',
    ],
    correctAnswer: 3,
    explanation: 'When checklists are high-level, two testers may use different test data and steps, so each may cover areas the other misses, resulting in greater overall coverage.',
  },
  {
    id: 28,
    domain: 'Chapter 4: Test Techniques',
    question: 'Which of the following provides the BEST example of a scenario-oriented acceptance criterion?',
    options: [
      'The application must allow users to delete their account and all associated data upon request',
      'When a customer adds an item to their cart and proceeds to checkout, they should be prompted to log in or create an account if they haven\'t already done so',
      'IF (contain(product(23).Name, cart.products())) THEN return FALSE',
      'The website must comply with the ICT Accessibility 508 Standards and ensure that all content is accessible to users with disabilities',
    ],
    correctAnswer: 1,
    explanation: 'A scenario-oriented acceptance criterion describes a specific example scenario that must be realized by the system, which option b does by describing the customer checkout flow.',
  },
  {
    id: 29,
    domain: 'Chapter 4: Test Techniques',
    question: 'You are using acceptance test-driven development and designing test cases based on the following user story: As a Regular or Special user, I want to be able to use my electronic floor card, to access specific floors. Acceptance Criteria: AC1: Regular users have access to floors 1 to 3. AC2: Floor 4 is only accessible to Special users. AC3: Special users have all the access rights of Regular users. Which test case is the MOST reasonable one to test AC3?',
    options: [
      'Check that a Regular user can access floors 1 and 3',
      'Check that a Regular user cannot access floor 4',
      'Check that a Special user can access floor 5',
      'Check that a Special user can access floors 1, 2 and 3',
    ],
    correctAnswer: 3,
    explanation: 'AC3 requires checking that Special users have the access rights of Regular users, so the test must verify a Special user can access the floors (1, 2, 3) that Regular users can access.',
  },
  {
    id: 30,
    domain: 'Chapter 5: Test Management',
    question: 'Which of the following is NOT a purpose of a test plan?',
    options: [
      'To define test data and expected results for component tests and component integration tests',
      'To define as exit criteria from the component test level that "100% statement coverage and 100% branch coverage must be achieved"',
      'To describe what fields the test progress report shall contain and what should be the form of this report',
      'To explain why system integration testing will be excluded from testing, although the test strategy requires this test level',
    ],
    correctAnswer: 0,
    explanation: 'A test plan may include test data requirements but not the detailed test data and expected results for individual test cases, since such detail is usually not yet known at the planning stage.',
  },
  {
    id: 31,
    domain: 'Chapter 5: Test Management',
    question: 'At the beginning of each iteration, the team estimates the amount of work (in person-days) they will need to complete during the iteration. Let E(n) be the estimated amount of work for iteration n, and let A(n) be the actual amount of work done in iteration n. From the third iteration, the team uses the following estimation model based on extrapolation: E(n) = (3*A(n-1) + A(n-2)) / 4. The graph shows the estimated and actual amount of work for the first four iterations. What is the estimated amount of work for iteration #5?',
    options: [
      '10.5 person-days',
      '8.25 person-days',
      '6.5 person-days',
      '9.4 person-days',
    ],
    correctAnswer: 2,
    explanation: 'From the graph, A(4)=6 and A(3)=8. Using the formula, E(5) = (3*6 + 8) / 4 = 26 / 4 = 6.5 person-days.',
  },
  {
    id: 32,
    domain: 'Chapter 5: Test Management',
    question: 'You are preparing a test execution schedule for executing seven test cases TC 1 to TC 7. The following figure includes the priorities of these test cases (1=highest priority, 3 = lowest priority). The figure also shows the dependencies between test cases using arrows. For instance, the arrow from TC 4 to TC 5 means that TC 5 can only be executed if TC 4 was previously executed. Which test case should be executed sixth?',
    options: [
      'TC 3',
      'TC 5',
      'TC 6',
      'TC 2',
    ],
    correctAnswer: 0,
    explanation: 'Considering both priorities and dependencies, the schedule is TC 4 – TC 7 – TC 1 – TC 2 – TC 5 – TC 3 – TC 6, making TC 3 the sixth test case to be executed.',
  },
  {
    id: 33,
    domain: 'Chapter 5: Test Management',
    question: 'What does the test pyramid model show?',
    options: [
      'That tests may have different priorities',
      'That tests may have different granularity',
      'That tests may require different coverage criteria',
      'That tests may depend on other tests',
    ],
    correctAnswer: 1,
    explanation: 'The test pyramid model illustrates that different tests have different levels of granularity, with many small low-level tests at the base and fewer broad high-level tests at the top.',
  },
  {
    id: 34,
    domain: 'Chapter 5: Test Management',
    question: 'What is the relationship between the testing quadrants, test levels and test types?',
    options: [
      'Testing quadrants represent particular combinations of test levels and test types, defining their location in the software development lifecycle',
      'Testing quadrants describe the degree of granularity of individual test types performed at each test level',
      'Testing quadrants assign the test types that can be performed to the test levels',
      'Testing quadrants group test levels and test types by several criteria such as targeting specific stakeholders',
    ],
    correctAnswer: 3,
    explanation: 'Testing quadrants group test levels, test types, test activities, techniques, and work products by criteria such as whether tests are business- or technology-facing and whether they support the team or critique the product.',
  },
  {
    id: 35,
    domain: 'Chapter 5: Test Management',
    question: 'Which of the following is an example of how product risk analysis may influence the thoroughness and scope of testing?',
    options: [
      'Continuous risk monitoring allows us to identify an emerging risk as soon as possible',
      'Risk identification allows us to implement risk mitigation activities and reduce the risk level',
      'The assessed risk level helps us to select the rigor of testing',
      'Risk analysis allows us to derive coverage items',
    ],
    correctAnswer: 2,
    explanation: 'The assessed risk level directly informs the rigor and thoroughness of testing performed, with higher-risk areas receiving more extensive testing than lower-risk ones.',
  },
  {
    id: 36,
    domain: 'Chapter 5: Test Management',
    question: 'Which of the following activities in the test process makes the MOST use of test progress reports?',
    options: [
      'Test design',
      'Test completion',
      'Test analysis',
      'Test planning',
    ],
    correctAnswer: 1,
    explanation: 'Test progress reports are most heavily used during test monitoring, test control, and test completion, where the test completion report consolidates information from progress reports.',
  },
  {
    id: 37,
    domain: 'Chapter 5: Test Management',
    question: 'Which of the following is NOT an example of how configuration management supports testing?',
    options: [
      'All commits to the repository are uniquely identified and version controlled',
      'All changes in the test environment elements are tracked',
      'All requirement specifications are referenced unambiguously in test plans',
      'All identified defects have an assigned status',
    ],
    correctAnswer: 3,
    explanation: 'Tracking defect status is the role of defect management, not configuration management. CM supports testing by uniquely identifying versions, tracking environment changes, and unambiguous referencing.',
  },
  {
    id: 38,
    domain: 'Chapter 5: Test Management',
    question: 'Consider the following defect report for a web-based shopping application: Application: WebShop v0.99. Defect: Login button not working. Steps to Reproduce: Launch the website, Click on the login button. Expected result: The user should be redirected to the login page. Actual result: The login button does not respond when clicked. Severity: High. Priority: Urgent. What is the MOST important information that is missing from this defect report?',
    options: [
      'Name of the tester and date',
      'Test environment elements and their version numbers',
      'Identification of the test object',
      'Impact on the interests of stakeholders',
    ],
    correctAnswer: 1,
    explanation: 'Browser and device information are the most important missing elements, since such defects can be browser- or device-specific and that information helps developers reproduce the issue.',
  },
  {
    id: 39,
    domain: 'Chapter 6: Test Tools and Automation',
    question: 'Tools from which of the following categories help with the organization of test cases, detected defects and configuration management?',
    options: [
      'Test execution and coverage tools',
      'Test design and implementation tools',
      'Defect management tools',
      'Test management tools',
    ],
    correctAnswer: 3,
    explanation: 'Test management tools increase process efficiency by facilitating management of the SDLC, requirements, tests, defects, and configuration management.',
  },
  {
    id: 40,
    domain: 'Chapter 6: Test Tools and Automation',
    question: 'Which of the following is MOST likely to be a benefit of test automation?',
    options: [
      'The capability of generating test cases without access to the test basis',
      'The achievement of increased coverage through more objective assessment',
      'The increase in test execution times available with higher processing power',
      'The prevention of human errors through greater consistency and repeatability',
    ],
    correctAnswer: 3,
    explanation: 'Test automation prevents human errors through greater consistency and repeatability: tests are consistently derived from requirements, test data is created systematically, and tests are executed in the same way each time.',
  },
];
